import {
  PrismaClient,
  Categories,
  Locations,
  DocumentType,
} from "@prisma/client";

const prisma = new PrismaClient();

const docDescriptions: { [key in DocumentType]: string } = {
  [DocumentType.PHOTO]: "Upload a recent passport-sized photograph",
  [DocumentType.AADHAR_CARD]:
    "Upload your Aadhar card or passport if you're not an Indian citizen",
  [DocumentType.MARKSHEET]: "Upload your latest academic marksheet",
  [DocumentType.FEE_PROOF]:
    "Upload proof of fee payment for the current semester",
  [DocumentType.COLLEGE_ID]: "Upload your valid college ID card",
};

async function main() {
  // Clear the event and related tables before seeding
  await prisma.team.deleteMany();
  await prisma.requiredDocument.deleteMany();
  await prisma.event.deleteMany();

  // Create the required documents
  const requiredDocuments = await Promise.all(
    Object.entries(docDescriptions).map(([documentType, description]) =>
      prisma.requiredDocument.create({
        data: {
          documentType: documentType as DocumentType,
          description,
        },
      })
    )
  );

  // Function to get required documents by type
  const getDocumentsByTypes = (types: DocumentType[]) => {
    return requiredDocuments.filter((doc) => types.includes(doc.documentType));
  };

  const athleticsDescription =
    "This event will follow standard athletic competition rules as defined by the Athletics Federation.";

  const sportsEvents = [
    {
      title: "Badminton (Men)",
      slug: "badminton-men",
      category: Categories.MALE,
      location: Locations.INDOOR,
      dateFrom: "2024-11-15T00:00:00Z",
      dateTo: "2024-11-17T23:59:59Z",
      rules:
        "Teams to be divided into 4 pools. Top teams to qualify for semifinals. Each match to be best of three games format. Semifinals to be best of five games format.",
      winnerPrize: 38500,
      winningTeamPrize: 22000,
      runnerUpTeamPrize: 12000,
      runnerUpPrize: 6000,
      minPlayers: 5,
      maxPlayers: 7,
      pricePerPlayer: 350,
      venue: "Shiv Nadar University Sports Complex",
      requiredDocumentTypes: [
        DocumentType.PHOTO,
        DocumentType.AADHAR_CARD,
        DocumentType.MARKSHEET,
        DocumentType.FEE_PROOF,
      ],
    },
    {
      title: "Badminton (Women)",
      slug: "badminton-women",
      category: Categories.FEMALE,
      location: Locations.INDOOR,
      dateFrom: "2024-11-15T00:00:00Z",
      dateTo: "2024-11-17T23:59:59Z",
      rules:
        "Teams to be divided into 4 pools. Top teams to qualify for semifinals. Each match to be best of three games format. Semifinals to be best of five games format.",
      winnerPrize: 38500,
      winningTeamPrize: 22000,
      runnerUpTeamPrize: 12000,
      runnerUpPrize: 6000,
      minPlayers: 3,
      maxPlayers: 5,
      pricePerPlayer: 350,
      venue: "Shiv Nadar University Sports Complex",
      requiredDocumentTypes: [
        DocumentType.PHOTO,
        DocumentType.AADHAR_CARD,
        DocumentType.MARKSHEET,
        DocumentType.FEE_PROOF,
      ],
    },
    {
      title: "Basketball (Men)",
      slug: "basketball-men",
      category: Categories.MALE,
      location: Locations.INDOOR,
      dateFrom: "2024-11-15T00:00:00Z",
      dateTo: "2024-11-17T23:59:59Z",
      rules:
        "FIBA rules applicable. Each quarter will be of 10 minutes with a 2 minutes break between them and a 5-minute break at half time.",
      winnerPrize: 84000,
      winningTeamPrize: 48000,
      runnerUpTeamPrize: 24000,
      runnerUpPrize: 12000,
      minPlayers: 8,
      maxPlayers: 12,
      pricePerPlayer: 400,
      venue: "Shiv Nadar University Sports Complex",
      requiredDocumentTypes: [
        DocumentType.PHOTO,
        DocumentType.AADHAR_CARD,
        DocumentType.MARKSHEET,
        DocumentType.FEE_PROOF,
      ],
    },
    {
      title: "Basketball (Women)",
      slug: "basketball-women",
      category: Categories.FEMALE,
      location: Locations.INDOOR,
      dateFrom: "2024-11-15T00:00:00Z",
      dateTo: "2024-11-17T23:59:59Z",
      rules:
        "FIBA rules applicable. Each quarter will be of 10 minutes with a 2 minutes break between them and a 5-minute break at half time.",
      winnerPrize: 84000,
      winningTeamPrize: 48000,
      runnerUpTeamPrize: 24000,
      runnerUpPrize: 12000,
      minPlayers: 8,
      maxPlayers: 12,
      pricePerPlayer: 400,
      venue: "Shiv Nadar University Sports Complex",
      requiredDocumentTypes: [
        DocumentType.PHOTO,
        DocumentType.AADHAR_CARD,
        DocumentType.MARKSHEET,
        DocumentType.FEE_PROOF,
      ],
    },
    {
      title: "Cricket (Men)",
      slug: "cricket-boys",
      category: Categories.MALE,
      location: Locations.OUTDOOR,
      dateFrom: "2024-11-15T00:00:00Z",
      dateTo: "2024-11-17T23:59:59Z",
      rules:
        "The tournament will be played on a knockout basis. Matches will be conducted with white balls. Teams have to play their matches in colored kits.",
      winnerPrize: 52500,
      winningTeamPrize: 30000,
      runnerUpTeamPrize: 15000,
      runnerUpPrize: 7500,
      minPlayers: 13,
      maxPlayers: 15,
      pricePerPlayer: 350,
      venue: "Shiv Nadar University Sports Complex",
      requiredDocumentTypes: [
        DocumentType.PHOTO,
        DocumentType.AADHAR_CARD,
        DocumentType.MARKSHEET,
        DocumentType.FEE_PROOF,
      ],
    },
    {
      title: "Cricket (Women)",
      slug: "cricket-girls",
      category: Categories.FEMALE,
      location: Locations.OUTDOOR,
      dateFrom: "2024-11-15T00:00:00Z",
      dateTo: "2024-11-17T23:59:59Z",
      rules:
        "The tournament will be played on a knockout basis. Matches will be conducted with white balls. Teams have to play their matches in colored kits.",
      winnerPrize: 22000,
      winningTeamPrize: 16500,
      runnerUpTeamPrize: 10000,
      runnerUpPrize: 5000,
      minPlayers: 13,
      maxPlayers: 15,
      pricePerPlayer: 350,
      venue: "Shiv Nadar University Sports Complex",
      requiredDocumentTypes: [
        DocumentType.PHOTO,
        DocumentType.AADHAR_CARD,
        DocumentType.MARKSHEET,
        DocumentType.FEE_PROOF,
      ],
    },
    {
      title: "Football (Men)",
      slug: "football-men",
      category: Categories.MALE,
      location: Locations.OUTDOOR,
      dateFrom: "2024-11-15T00:00:00Z",
      dateTo: "2024-11-17T23:59:59Z",
      rules:
        "The game will be played in accordance with the rules established by FIFA.",
      winnerPrize: 91000,
      winningTeamPrize: 52000,
      runnerUpTeamPrize: 26000,
      runnerUpPrize: 13000,
      minPlayers: 14,
      maxPlayers: 16,
      pricePerPlayer: 250,
      venue: "Shiv Nadar University Sports Complex",
      requiredDocumentTypes: [
        DocumentType.PHOTO,
        DocumentType.AADHAR_CARD,
        DocumentType.MARKSHEET,
        DocumentType.FEE_PROOF,
      ],
    },
    {
      title: "Futsal (Women)",
      slug: "futsal-women",
      category: Categories.FEMALE,
      location: Locations.OUTDOOR,
      dateFrom: "2024-11-15T00:00:00Z",
      dateTo: "2024-11-17T23:59:59Z",
      rules:
        "6 vs 6 format one of which will be the goalkeeper. Duration of matches: 30 minutes (2*15 minutes) with a 10-minute break between halves.",
      winnerPrize: 91000,
      winningTeamPrize: 52000,
      runnerUpTeamPrize: 26000,
      runnerUpPrize: 13000,
      minPlayers: 8,
      maxPlayers: 10,
      pricePerPlayer: 250,
      venue: "Shiv Nadar University Sports Complex",
      requiredDocumentTypes: [
        DocumentType.PHOTO,
        DocumentType.AADHAR_CARD,
        DocumentType.MARKSHEET,
        DocumentType.FEE_PROOF,
      ],
    },
    {
      title: "Squash (Men)",
      slug: "squash-men",
      category: Categories.MALE,
      location: Locations.INDOOR,
      dateFrom: "2024-11-15T00:00:00Z",
      dateTo: "2024-11-17T23:59:59Z",
      rules:
        "Rules of the Squash Rackets Federation of India will be applicable. The tournament shall be played in singles only and on a league-cum knockout basis. The knockout system shall be followed only amongst the first four teams.",
      winnerPrize: 24500,
      winningTeamPrize: 14000,
      runnerUpTeamPrize: 7000,
      runnerUpPrize: 3500,
      minPlayers: 3,
      maxPlayers: 6,
      pricePerPlayer: 300,
      venue: "Shiv Nadar University Sports Complex",
      requiredDocumentTypes: [
        DocumentType.PHOTO,
        DocumentType.AADHAR_CARD,
        DocumentType.MARKSHEET,
        DocumentType.FEE_PROOF,
      ],
    },
    {
      title: "Squash (Women)",
      slug: "squash-women",
      category: Categories.FEMALE,
      location: Locations.INDOOR,
      dateFrom: "2024-11-15T00:00:00Z",
      dateTo: "2024-11-17T23:59:59Z",
      rules:
        "Rules of the Squash Rackets Federation of India will be applicable. The tournament shall be played in singles only and on a league-cum knockout basis. The knockout system shall be followed only amongst the first four teams. Women’s squash will be an individual event.",
      winnerPrize: 24500,
      winningTeamPrize: 14000,
      runnerUpTeamPrize: 7000,
      runnerUpPrize: 3500,
      minPlayers: 3,
      maxPlayers: 6,
      pricePerPlayer: 300,
      venue: "Shiv Nadar University Sports Complex",
      requiredDocumentTypes: [
        DocumentType.PHOTO,
        DocumentType.AADHAR_CARD,
        DocumentType.MARKSHEET,
        DocumentType.FEE_PROOF,
      ],
    },
    {
      title: "Table Tennis (Men)",
      slug: "table-tennis-men",
      category: Categories.MALE,
      location: Locations.INDOOR,
      dateFrom: "2024-11-15T00:00:00Z",
      dateTo: "2024-11-17T23:59:59Z",
      rules:
        "AIU (Association of Indian Universities) Rules will be followed for the tournament. The format of the match for Men will be a team event having 3 SINGLES and 2 REVERSE SINGLES.",
      winnerPrize: 35000,
      winningTeamPrize: 20000,
      runnerUpTeamPrize: 10000,
      runnerUpPrize: 5000,
      minPlayers: 3,
      maxPlayers: 5,
      pricePerPlayer: 300,
      venue: "Shiv Nadar University Sports Complex",
      requiredDocumentTypes: [
        DocumentType.PHOTO,
        DocumentType.AADHAR_CARD,
        DocumentType.MARKSHEET,
        DocumentType.FEE_PROOF,
      ],
    },
    {
      title: "Table Tennis (Women)",
      slug: "table-tennis-women",
      category: Categories.FEMALE,
      location: Locations.INDOOR,
      dateFrom: "2024-11-15T00:00:00Z",
      dateTo: "2024-11-17T23:59:59Z",
      rules:
        "AIU (Association of Indian Universities) Rules will be followed for the tournament. The format of the match for Women will be a team event having 2 SINGLES and 1 DOUBLES.",
      winnerPrize: 35000,
      winningTeamPrize: 20000,
      runnerUpTeamPrize: 10000,
      runnerUpPrize: 5000,
      minPlayers: 3,
      maxPlayers: 5,
      pricePerPlayer: 300,
      venue: "Shiv Nadar University Sports Complex",
      requiredDocumentTypes: [
        DocumentType.PHOTO,
        DocumentType.AADHAR_CARD,
        DocumentType.MARKSHEET,
        DocumentType.FEE_PROOF,
      ],
    },
    {
      title: "Tennis (Men)",
      slug: "tennis-men",
      category: Categories.MALE,
      location: Locations.INDOOR,
      dateFrom: "2024-11-15T00:00:00Z",
      dateTo: "2024-11-17T23:59:59Z",
      rules:
        "International Tennis Federation rules will be applicable. Tournament will be played in singles and doubles format.",
      winnerPrize: 28000,
      winningTeamPrize: 16000,
      runnerUpTeamPrize: 8000,
      runnerUpPrize: 4000,
      minPlayers: 4,
      maxPlayers: 8,
      pricePerPlayer: 400,
      venue: "Shiv Nadar University Sports Complex",
      requiredDocumentTypes: [
        DocumentType.PHOTO,
        DocumentType.AADHAR_CARD,
        DocumentType.MARKSHEET,
        DocumentType.FEE_PROOF,
      ],
    },
    {
      title: "Tennis (Women)",
      slug: "tennis-women",
      category: Categories.FEMALE,
      location: Locations.INDOOR,
      dateFrom: "2024-11-15T00:00:00Z",
      dateTo: "2024-11-17T23:59:59Z",
      rules:
        "International Tennis Federation rules will be applicable. Tournament will be played in singles and doubles format.",
      winnerPrize: 28000,
      winningTeamPrize: 16000,
      runnerUpTeamPrize: 8000,
      runnerUpPrize: 4000,
      minPlayers: 4,
      maxPlayers: 8,
      pricePerPlayer: 400,
      venue: "Shiv Nadar University Sports Complex",
      requiredDocumentTypes: [
        DocumentType.PHOTO,
        DocumentType.AADHAR_CARD,
        DocumentType.MARKSHEET,
        DocumentType.FEE_PROOF,
      ],
    },
    {
      title: "Volleyball (Men)",
      slug: "volleyball-men",
      category: Categories.MALE,
      location: Locations.OUTDOOR,
      dateFrom: "2024-11-15T00:00:00Z",
      dateTo: "2024-11-17T23:59:59Z",
      rules:
        "International laws would be followed according to FIVB rules. All league matches will be of 3 sets. In the case of a 1-1 tie, the deciding 3rd set is played to 15 points. The semi-finals and final will be of 5 sets.",
      winnerPrize: 84000,
      winningTeamPrize: 48000,
      runnerUpTeamPrize: 24000,
      runnerUpPrize: 12000,
      minPlayers: 8,
      maxPlayers: 12,
      pricePerPlayer: 400,
      venue: "Shiv Nadar University Sports Complex",
      requiredDocumentTypes: [
        DocumentType.PHOTO,
        DocumentType.AADHAR_CARD,
        DocumentType.MARKSHEET,
        DocumentType.FEE_PROOF,
      ],
    },
    {
      title: "Volleyball (Women)",
      slug: "volleyball-women",
      category: Categories.FEMALE,
      location: Locations.OUTDOOR,
      dateFrom: "2024-11-15T00:00:00Z",
      dateTo: "2024-11-17T23:59:59Z",
      rules:
        "International laws would be followed according to FIVB rules. All league matches will be of 3 sets. In the case of a 1-1 tie, the deciding 3rd set is played to 15 points. The semi-finals and final will be of 5 sets.",
      winnerPrize: 84000,
      winningTeamPrize: 48000,
      runnerUpTeamPrize: 24000,
      runnerUpPrize: 12000,
      minPlayers: 8,
      maxPlayers: 12,
      pricePerPlayer: 400,
      venue: "Shiv Nadar University Sports Complex",
      requiredDocumentTypes: [
        DocumentType.PHOTO,
        DocumentType.AADHAR_CARD,
        DocumentType.MARKSHEET,
        DocumentType.FEE_PROOF,
      ],
    },
    {
      title: "Powerlifting",
      slug: "powerlifting",
      category: Categories.MIXED,
      location: Locations.INDOOR,
      dateFrom: "2024-11-15T00:00:00Z",
      dateTo: "2024-11-17T23:59:59Z",
      rules:
        "The competition will adhere to a classic 3-lift sequence in the following order: 1. Squats 2. Bench Press 3. Deadlift. The competition will follow the IPF Powerlifting Rulebook 2024 for rules on performance and disqualification.",
      winnerPrize: 3000,
      winningTeamPrize: 2000,
      runnerUpTeamPrize: 1000,
      runnerUpPrize: 500,
      minPlayers: 1,
      maxPlayers: 10,
      pricePerPlayer: 200,
      venue: "Shiv Nadar University Sports Complex",
      requiredDocumentTypes: [
        DocumentType.PHOTO,
        DocumentType.AADHAR_CARD,
        DocumentType.MARKSHEET,
        DocumentType.FEE_PROOF,
      ],
    },
    // Men's Track Events
    {
      title: "100m (Men)",
      slug: "100m-men",
      category: Categories.MALE,
      location: Locations.OUTDOOR,
      dateFrom: "2024-11-15T00:00:00Z",
      dateTo: "2024-11-17T23:59:59Z",
      rules: athleticsDescription,
      winnerPrize: 10000,
      winningTeamPrize: 0,
      runnerUpTeamPrize: 0,
      runnerUpPrize: 5000,
      minPlayers: 1,
      maxPlayers: 8,
      pricePerPlayer: 150,
      venue: "Shiv Nadar University Sports Complex",
      requiredDocumentTypes: [
        DocumentType.PHOTO,
        DocumentType.AADHAR_CARD,
        DocumentType.MARKSHEET,
        DocumentType.FEE_PROOF,
      ],
    },
    {
      title: "200m (Men)",
      slug: "200m-men",
      category: Categories.MALE,
      location: Locations.OUTDOOR,
      dateFrom: "2024-11-15T00:00:00Z",
      dateTo: "2024-11-17T23:59:59Z",
      rules: athleticsDescription,
      winnerPrize: 10000,
      winningTeamPrize: 0,
      runnerUpTeamPrize: 0,
      runnerUpPrize: 5000,
      minPlayers: 1,
      maxPlayers: 8,
      pricePerPlayer: 150,
      venue: "Shiv Nadar University Sports Complex",
      requiredDocumentTypes: [
        DocumentType.PHOTO,
        DocumentType.AADHAR_CARD,
        DocumentType.MARKSHEET,
        DocumentType.FEE_PROOF,
      ],
    },
    {
      title: "400m (Men)",
      slug: "400m-men",
      category: Categories.MALE,
      location: Locations.OUTDOOR,
      dateFrom: "2024-11-15T00:00:00Z",
      dateTo: "2024-11-17T23:59:59Z",
      rules: athleticsDescription,
      winnerPrize: 10000,
      winningTeamPrize: 0,
      runnerUpTeamPrize: 0,
      runnerUpPrize: 5000,
      minPlayers: 1,
      maxPlayers: 8,
      pricePerPlayer: 150,
      venue: "Shiv Nadar University Sports Complex",
      requiredDocumentTypes: [
        DocumentType.PHOTO,
        DocumentType.AADHAR_CARD,
        DocumentType.MARKSHEET,
        DocumentType.FEE_PROOF,
      ],
    },
    {
      title: "800m (Men)",
      slug: "800m-men",
      category: Categories.MALE,
      location: Locations.OUTDOOR,
      dateFrom: "2024-11-15T00:00:00Z",
      dateTo: "2024-11-17T23:59:59Z",
      rules: athleticsDescription,
      winnerPrize: 10000,
      winningTeamPrize: 0,
      runnerUpTeamPrize: 0,
      runnerUpPrize: 5000,
      minPlayers: 1,
      maxPlayers: 8,
      pricePerPlayer: 150,
      venue: "Shiv Nadar University Sports Complex",
      requiredDocumentTypes: [
        DocumentType.PHOTO,
        DocumentType.AADHAR_CARD,
        DocumentType.MARKSHEET,
        DocumentType.FEE_PROOF,
      ],
    },
    {
      title: "1500m (Men)",
      slug: "1500m-men",
      category: Categories.MALE,
      location: Locations.OUTDOOR,
      dateFrom: "2024-11-15T00:00:00Z",
      dateTo: "2024-11-17T23:59:59Z",
      rules: athleticsDescription,
      winnerPrize: 10000,
      winningTeamPrize: 0,
      runnerUpTeamPrize: 0,
      runnerUpPrize: 5000,
      minPlayers: 1,
      maxPlayers: 8,
      pricePerPlayer: 150,
      venue: "Shiv Nadar University Sports Complex",
      requiredDocumentTypes: [
        DocumentType.PHOTO,
        DocumentType.AADHAR_CARD,
        DocumentType.MARKSHEET,
        DocumentType.FEE_PROOF,
      ],
    },
    {
      title: "5000m (Men)",
      slug: "5000m-men",
      category: Categories.MALE,
      location: Locations.OUTDOOR,
      dateFrom: "2024-11-15T00:00:00Z",
      dateTo: "2024-11-17T23:59:59Z",
      rules: athleticsDescription,
      winnerPrize: 10000,
      winningTeamPrize: 0,
      runnerUpTeamPrize: 0,
      runnerUpPrize: 5000,
      minPlayers: 1,
      maxPlayers: 8,
      pricePerPlayer: 150,
      venue: "Shiv Nadar University Sports Complex",
      requiredDocumentTypes: [
        DocumentType.PHOTO,
        DocumentType.AADHAR_CARD,
        DocumentType.MARKSHEET,
        DocumentType.FEE_PROOF,
      ],
    },
    {
      title: "4x100m Relay (Men)",
      slug: "4x100m-men",
      category: Categories.MALE,
      location: Locations.OUTDOOR,
      dateFrom: "2024-11-15T00:00:00Z",
      dateTo: "2024-11-17T23:59:59Z",
      rules: athleticsDescription,
      winnerPrize: 20000,
      winningTeamPrize: 10000,
      runnerUpTeamPrize: 5000,
      runnerUpPrize: 0,
      minPlayers: 4,
      maxPlayers: 4,
      pricePerPlayer: 600,
      venue: "Shiv Nadar University Sports Complex",
      requiredDocumentTypes: [
        DocumentType.PHOTO,
        DocumentType.AADHAR_CARD,
        DocumentType.MARKSHEET,
        DocumentType.FEE_PROOF,
      ],
    },
    {
      title: "4x400m Relay (Men)",
      slug: "4x400m-men",
      category: Categories.MALE,
      location: Locations.OUTDOOR,
      dateFrom: "2024-11-15T00:00:00Z",
      dateTo: "2024-11-17T23:59:59Z",
      rules: athleticsDescription,
      winnerPrize: 20000,
      winningTeamPrize: 10000,
      runnerUpTeamPrize: 5000,
      runnerUpPrize: 0,
      minPlayers: 4,
      maxPlayers: 4,
      pricePerPlayer: 600,
      venue: "Shiv Nadar University Sports Complex",
      requiredDocumentTypes: [
        DocumentType.PHOTO,
        DocumentType.AADHAR_CARD,
        DocumentType.MARKSHEET,
        DocumentType.FEE_PROOF,
      ],
    },
    // Men's Throws Events
    {
      title: "Shot Put (Men)",
      slug: "shot-put-men",
      category: Categories.MALE,
      location: Locations.OUTDOOR,
      dateFrom: "2024-11-15T00:00:00Z",
      dateTo: "2024-11-17T23:59:59Z",
      rules: athleticsDescription,
      winnerPrize: 10000,
      winningTeamPrize: 0,
      runnerUpTeamPrize: 0,
      runnerUpPrize: 5000,
      minPlayers: 1,
      maxPlayers: 8,
      pricePerPlayer: 150,
      venue: "Shiv Nadar University Sports Complex",
      requiredDocumentTypes: [
        DocumentType.PHOTO,
        DocumentType.AADHAR_CARD,
        DocumentType.MARKSHEET,
        DocumentType.FEE_PROOF,
      ],
    },
    {
      title: "Discus Throw (Men)",
      slug: "discus-throw-men",
      category: Categories.MALE,
      location: Locations.OUTDOOR,
      dateFrom: "2024-11-15T00:00:00Z",
      dateTo: "2024-11-17T23:59:59Z",
      rules: athleticsDescription,
      winnerPrize: 10000,
      winningTeamPrize: 0,
      runnerUpTeamPrize: 0,
      runnerUpPrize: 5000,
      minPlayers: 1,
      maxPlayers: 8,
      pricePerPlayer: 150,
      venue: "Shiv Nadar University Sports Complex",
      requiredDocumentTypes: [
        DocumentType.PHOTO,
        DocumentType.AADHAR_CARD,
        DocumentType.MARKSHEET,
        DocumentType.FEE_PROOF,
      ],
    },
    // Men's Jumps Events
    {
      title: "Long Jump (Men)",
      slug: "long-jump-men",
      category: Categories.MALE,
      location: Locations.OUTDOOR,
      dateFrom: "2024-11-15T00:00:00Z",
      dateTo: "2024-11-17T23:59:59Z",
      rules: athleticsDescription,
      winnerPrize: 10000,
      winningTeamPrize: 0,
      runnerUpTeamPrize: 0,
      runnerUpPrize: 5000,
      minPlayers: 1,
      maxPlayers: 8,
      pricePerPlayer: 150,
      venue: "Shiv Nadar University Sports Complex",
      requiredDocumentTypes: [
        DocumentType.PHOTO,
        DocumentType.AADHAR_CARD,
        DocumentType.MARKSHEET,
        DocumentType.FEE_PROOF,
      ],
    },
    // Women's Track Events
    {
      title: "100m (Women)",
      slug: "100m-women",
      category: Categories.FEMALE,
      location: Locations.OUTDOOR,
      dateFrom: "2024-11-15T00:00:00Z",
      dateTo: "2024-11-17T23:59:59Z",
      rules: athleticsDescription,
      winnerPrize: 10000,
      winningTeamPrize: 0,
      runnerUpTeamPrize: 0,
      runnerUpPrize: 5000,
      minPlayers: 1,
      maxPlayers: 8,
      pricePerPlayer: 150,
      venue: "Shiv Nadar University Sports Complex",
      requiredDocumentTypes: [
        DocumentType.PHOTO,
        DocumentType.AADHAR_CARD,
        DocumentType.MARKSHEET,
        DocumentType.FEE_PROOF,
      ],
    },
    {
      title: "200m (Women)",
      slug: "200m-women",
      category: Categories.FEMALE,
      location: Locations.OUTDOOR,
      dateFrom: "2024-11-15T00:00:00Z",
      dateTo: "2024-11-17T23:59:59Z",
      rules: athleticsDescription,
      winnerPrize: 10000,
      winningTeamPrize: 0,
      runnerUpTeamPrize: 0,
      runnerUpPrize: 5000,
      minPlayers: 1,
      maxPlayers: 8,
      pricePerPlayer: 150,
      venue: "Shiv Nadar University Sports Complex",
      requiredDocumentTypes: [
        DocumentType.PHOTO,
        DocumentType.AADHAR_CARD,
        DocumentType.MARKSHEET,
        DocumentType.FEE_PROOF,
      ],
    },
    {
      title: "400m (Women)",
      slug: "400m-women",
      category: Categories.FEMALE,
      location: Locations.OUTDOOR,
      dateFrom: "2024-11-15T00:00:00Z",
      dateTo: "2024-11-17T23:59:59Z",
      rules: athleticsDescription,
      winnerPrize: 10000,
      winningTeamPrize: 0,
      runnerUpTeamPrize: 0,
      runnerUpPrize: 5000,
      minPlayers: 1,
      maxPlayers: 8,
      pricePerPlayer: 150,
      venue: "Shiv Nadar University Sports Complex",
      requiredDocumentTypes: [
        DocumentType.PHOTO,
        DocumentType.AADHAR_CARD,
        DocumentType.MARKSHEET,
        DocumentType.FEE_PROOF,
      ],
    },
    {
      title: "800m (Women)",
      slug: "800m-women",
      category: Categories.FEMALE,
      location: Locations.OUTDOOR,
      dateFrom: "2024-11-15T00:00:00Z",
      dateTo: "2024-11-17T23:59:59Z",
      rules: athleticsDescription,
      winnerPrize: 10000,
      winningTeamPrize: 0,
      runnerUpTeamPrize: 0,
      runnerUpPrize: 5000,
      minPlayers: 1,
      maxPlayers: 8,
      pricePerPlayer: 150,
      venue: "Shiv Nadar University Sports Complex",
      requiredDocumentTypes: [
        DocumentType.PHOTO,
        DocumentType.AADHAR_CARD,
        DocumentType.MARKSHEET,
        DocumentType.FEE_PROOF,
      ],
    },
    {
      title: "1500m (Women)",
      slug: "1500m-women",
      category: Categories.FEMALE,
      location: Locations.OUTDOOR,
      dateFrom: "2024-11-15T00:00:00Z",
      dateTo: "2024-11-17T23:59:59Z",
      rules: athleticsDescription,
      winnerPrize: 10000,
      winningTeamPrize: 0,
      runnerUpTeamPrize: 0,
      runnerUpPrize: 5000,
      minPlayers: 1,
      maxPlayers: 8,
      pricePerPlayer: 150,
      venue: "Shiv Nadar University Sports Complex",
      requiredDocumentTypes: [
        DocumentType.PHOTO,
        DocumentType.AADHAR_CARD,
        DocumentType.MARKSHEET,
        DocumentType.FEE_PROOF,
      ],
    },
    {
      title: "4x100m Relay (Women)",
      slug: "4x100m-women",
      category: Categories.FEMALE,
      location: Locations.OUTDOOR,
      dateFrom: "2024-11-15T00:00:00Z",
      dateTo: "2024-11-17T23:59:59Z",
      rules: athleticsDescription,
      winnerPrize: 20000,
      winningTeamPrize: 10000,
      runnerUpTeamPrize: 5000,
      runnerUpPrize: 0,
      minPlayers: 4,
      maxPlayers: 4,
      pricePerPlayer: 600,
      venue: "Shiv Nadar University Sports Complex",
      requiredDocumentTypes: [
        DocumentType.PHOTO,
        DocumentType.AADHAR_CARD,
        DocumentType.MARKSHEET,
        DocumentType.FEE_PROOF,
      ],
    },
    {
      title: "4x400m Relay (Women)",
      slug: "4x400m-women",
      category: Categories.FEMALE,
      location: Locations.OUTDOOR,
      dateFrom: "2024-11-15T00:00:00Z",
      dateTo: "2024-11-17T23:59:59Z",
      rules: athleticsDescription,
      winnerPrize: 20000,
      winningTeamPrize: 10000,
      runnerUpTeamPrize: 5000,
      runnerUpPrize: 0,
      minPlayers: 4,
      maxPlayers: 4,
      pricePerPlayer: 600,
      venue: "Shiv Nadar University Sports Complex",
      requiredDocumentTypes: [
        DocumentType.PHOTO,
        DocumentType.AADHAR_CARD,
        DocumentType.MARKSHEET,
        DocumentType.FEE_PROOF,
      ],
    },
    // Women's Throws Events
    {
      title: "Shot Put (Women)",
      slug: "shot-put-women",
      category: Categories.FEMALE,
      location: Locations.OUTDOOR,
      dateFrom: "2024-11-15T00:00:00Z",
      dateTo: "2024-11-17T23:59:59Z",
      rules: athleticsDescription,
      winnerPrize: 10000,
      winningTeamPrize: 0,
      runnerUpTeamPrize: 0,
      runnerUpPrize: 5000,
      minPlayers: 1,
      maxPlayers: 8,
      pricePerPlayer: 150,
      venue: "Shiv Nadar University Sports Complex",
      requiredDocumentTypes: [
        DocumentType.PHOTO,
        DocumentType.AADHAR_CARD,
        DocumentType.MARKSHEET,
        DocumentType.FEE_PROOF,
      ],
    },
    {
      title: "Discus Throw (Women)",
      slug: "discus-throw-women",
      category: Categories.FEMALE,
      location: Locations.OUTDOOR,
      dateFrom: "2024-11-15T00:00:00Z",
      dateTo: "2024-11-17T23:59:59Z",
      rules: athleticsDescription,
      winnerPrize: 10000,
      winningTeamPrize: 0,
      runnerUpTeamPrize: 0,
      runnerUpPrize: 5000,
      minPlayers: 1,
      maxPlayers: 8,
      pricePerPlayer: 150,
      venue: "Shiv Nadar University Sports Complex",
      requiredDocumentTypes: [
        DocumentType.PHOTO,
        DocumentType.AADHAR_CARD,
        DocumentType.MARKSHEET,
        DocumentType.FEE_PROOF,
      ],
    },
    // Women's Jumps Events
    {
      title: "Long Jump (Women)",
      slug: "long-jump-women",
      category: Categories.FEMALE,
      location: Locations.OUTDOOR,
      dateFrom: "2024-11-15T00:00:00Z",
      dateTo: "2024-11-17T23:59:59Z",
      rules: athleticsDescription,
      winnerPrize: 10000,
      winningTeamPrize: 0,
      runnerUpTeamPrize: 0,
      runnerUpPrize: 5000,
      minPlayers: 1,
      maxPlayers: 8,
      pricePerPlayer: 150,
      venue: "Shiv Nadar University Sports Complex",
      requiredDocumentTypes: [
        DocumentType.PHOTO,
        DocumentType.AADHAR_CARD,
        DocumentType.MARKSHEET,
        DocumentType.FEE_PROOF,
      ],
    },
  ];

  for (const event of sportsEvents) {
    await prisma.event.create({
      data: {
        name: event.title,
        slug: event.slug,
        category: event.category,
        location: event.location,
        dateFrom: event.dateFrom,
        dateTo: event.dateTo,
        venue: event.venue,
        rules: event.rules,
        winnerPrize: event.winnerPrize,
        winningTeamPrize: event.winningTeamPrize,
        runnerUpTeamPrize: event.runnerUpTeamPrize,
        runnerUpPrize: event.runnerUpPrize,
        minPlayers: event.minPlayers,
        maxPlayers: event.maxPlayers,
        pricePerPlayer: event.pricePerPlayer,
        requiredDocuments: {
          connect: getDocumentsByTypes(event.requiredDocumentTypes).map(
            (doc) => ({ id: doc.id })
          ),
        },
      },
    });
  }

  console.log("Sports events seeded successfully");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
