import { PrismaClient, Categories, Locations } from '@prisma/client';

const prisma = new PrismaClient();

async function main() {
  // Clear the event table before seeding
  await prisma.event.deleteMany();

  const sportsEvents = [
    {
      title: "Football",
      slug: "football",
      category: Categories.MALE,
      location: Locations.OUTDOOR,
      dateFrom: "2024-11-15T00:00:00Z",
      dateTo: "2024-11-17T23:59:59Z",
      rules: "The game will be played in accordance with the rules established by FIFA.",
      winnerPrize: 3500,
      winningTeamPrize: 2000,
      runnerUpTeamPrize: 775,
      runnerUpPrize: 775,
      minPlayers: 14,
      maxPlayers: 16,
      pricePerPlayer: 250,
      venue: "Shiv Nadar University Sports Complex",
    },
    {
      title: "Badminton",
      slug: "badminton",
      category: Categories.MIXED,
      location: Locations.INDOOR,
      dateFrom: "2024-11-15T00:00:00Z",
      dateTo: "2024-11-17T23:59:59Z",
      rules: "Badminton will be played on a round-robin cum knock-out basis.",
      winnerPrize: 3500,
      winningTeamPrize: 2000,
      runnerUpTeamPrize: 775,
      runnerUpPrize: 775,
      minPlayers: 3,
      maxPlayers: 7,
      pricePerPlayer: 350,
      venue: "Shiv Nadar University Sports Complex",
    },
    {
      title: "Athletics",
      slug: "athletics",
      category: Categories.MALE,
      location: Locations.OUTDOOR,
      dateFrom: "2024-11-15T00:00:00Z",
      dateTo: "2024-11-17T23:59:59Z",
      rules: "Maximum number of Events allowed per athlete: 3 Individuals + 2 relays.",
      winnerPrize: 250,
      winningTeamPrize: 0,
      runnerUpTeamPrize: 0,
      runnerUpPrize: 0,
      minPlayers: 1,
      maxPlayers: 5,
      pricePerPlayer: 250,
      venue: "Shiv Nadar University Sports Complex",
    },
    {
      title: "Basketball",
      slug: "basketball",
      category: Categories.MALE,
      location: Locations.INDOOR,
      dateFrom: "2024-11-15T00:00:00Z",
      dateTo: "2024-11-17T23:59:59Z",
      rules: "FIBA rules applicable. Each quarter will be 10 minutes with a 2-minute break between the quarters and 5 minutes at half time.",
      winnerPrize: 3500,
      winningTeamPrize: 2000,
      runnerUpTeamPrize: 775,
      runnerUpPrize: 775,
      minPlayers: 8,
      maxPlayers: 12,
      pricePerPlayer: 350,
      venue: "Shiv Nadar University Sports Complex",
    },
    {
      title: "Powerlifting",
      slug: "powerlifting",
      category: Categories.MALE,
      location: Locations.INDOOR,
      dateFrom: "2024-11-15T00:00:00Z",
      dateTo: "2024-11-17T23:59:59Z",
      rules: "The competition will be conducted under the rules of the International Powerlifting Federation.",
      winnerPrize: 1000,
      winningTeamPrize: 750,
      runnerUpTeamPrize: 250,
      runnerUpPrize: 250,
      minPlayers: 1,
      maxPlayers: 1,
      pricePerPlayer: 1000,
      venue: "Shiv Nadar University Sports Complex",
    },
    {
      title: "Cricket",
      slug: "cricket",
      category: Categories.MALE,
      location: Locations.OUTDOOR,
      dateFrom: "2024-11-15T00:00:00Z",
      dateTo: "2024-11-17T23:59:59Z",
      rules: "The tournament will be played on a knockout basis. Matches will be conducted with white balls. Teams have to play their matches in colored kits.",
      winnerPrize: 3500,
      winningTeamPrize: 2000,
      runnerUpTeamPrize: 775,
      runnerUpPrize: 775,
      minPlayers: 13,
      maxPlayers: 15,
      pricePerPlayer: 350,
      venue: "Shiv Nadar University Sports Complex",
    },
    {
      title: "Volleyball",
      slug: "volleyball",
      category: Categories.MALE,
      location: Locations.INDOOR,
      dateFrom: "2024-11-15T00:00:00Z",
      dateTo: "2024-11-17T23:59:59Z",
      rules: "All league matches will be of 3 sets. The semi-finals and final will be of 5 sets.",
      winnerPrize: 3500,
      winningTeamPrize: 2000,
      runnerUpTeamPrize: 775,
      runnerUpPrize: 775,
      minPlayers: 6,
      maxPlayers: 12,
      pricePerPlayer: 350,
      venue: "Shiv Nadar University Sports Complex",
    },
    {
      title: "Table Tennis",
      slug: "table-tennis",
      category: Categories.MALE,
      location: Locations.INDOOR,
      dateFrom: "2024-11-15T00:00:00Z",
      dateTo: "2024-11-17T23:59:59Z",
      rules: "The tournament will be played on a single-league basis. Repetition of players is not allowed for Men’s matches.",
      winnerPrize: 3500,
      winningTeamPrize: 2000,
      runnerUpTeamPrize: 775,
      runnerUpPrize: 775,
      minPlayers: 3,
      maxPlayers: 5,
      pricePerPlayer: 350,
      venue: "Shiv Nadar University Sports Complex",
    },
    {
      title: "Lawn Tennis",
      slug: "lawn-tennis",
      category: Categories.MALE,
      location: Locations.OUTDOOR,
      dateFrom: "2024-11-15T00:00:00Z",
      dateTo: "2024-11-17T23:59:59Z",
      rules: "The top two teams from each pool, at the end of the league stage, will qualify for the semifinals.",
      winnerPrize: 3500,
      winningTeamPrize: 2000,
      runnerUpTeamPrize: 775,
      runnerUpPrize: 775,
      minPlayers: 3,
      maxPlayers: 5,
      pricePerPlayer: 350,
      venue: "Shiv Nadar University Sports Complex",
    },
    {
      title: "Squash",
      slug: "squash",
      category: Categories.MALE,
      location: Locations.INDOOR,
      dateFrom: "2024-11-15T00:00:00Z",
      dateTo: "2024-11-17T23:59:59Z",
      rules: "The tournament shall be played in singles only and on a league-cum knock-out basis.",
      winnerPrize: 3500,
      winningTeamPrize: 2000,
      runnerUpTeamPrize: 775,
      runnerUpPrize: 775,
      minPlayers: 3,
      maxPlayers: 6,
      pricePerPlayer: 350,
      venue: "Shiv Nadar University Sports Complex",
    },
    {
      title: "Chess",
      slug: "chess",
      category: Categories.MIXED,
      location: Locations.INDOOR,
      dateFrom: "2024-11-15T00:00:00Z",
      dateTo: "2024-11-17T23:59:59Z",
      rules: "The time format for the game will be 25 minutes + 10 seconds increment per move. Each team will have 4 - 5 players.",
      winnerPrize: 500,
      winningTeamPrize: 0,
      runnerUpTeamPrize: 0,
      runnerUpPrize: 0,
      minPlayers: 4,
      maxPlayers: 5,
      pricePerPlayer: 500,
      venue: "Shiv Nadar University Sports Complex",
    },
    {
      title: "Valorant (E-Sport)",
      slug: "valorant",
      category: Categories.MIXED,
      location: Locations.VIRTUAL,
      dateFrom: "2024-11-15T00:00:00Z",
      dateTo: "2024-11-17T23:59:59Z",
      rules: "Valorant rules as per the official tournament guide.",
      winnerPrize: 2000,
      winningTeamPrize: 150,
      runnerUpTeamPrize: 0,
      runnerUpPrize: 0,
      minPlayers: 5,
      maxPlayers: 5,
      pricePerPlayer: 200,
      venue: "Online",
    },
    {
      title: "FIFA (E-Sport)",
      slug: "fifa",
      category: Categories.MIXED,
      location: Locations.VIRTUAL,
      dateFrom: "2024-11-15T00:00:00Z",
      dateTo: "2024-11-17T23:59:59Z",
      rules: "FIFA tournament rules as per the official guide.",
      winnerPrize: 2000,
      winningTeamPrize: 150,
      runnerUpTeamPrize: 0,
      runnerUpPrize: 0,
      minPlayers: 1,
      maxPlayers: 1,
      pricePerPlayer: 200,
      venue: "Online",
    }
  ];

  for (const event of sportsEvents) {
    await prisma.event.create({
      data: {
        name: event.title,
        slug: event.slug,
        category: event.category,
        location: event.location,
        dateFrom: event.dateFrom,
        dateTo: event.dateTo,
        venue: event.venue,
        rules: event.rules,
        winnerPrize: event.winnerPrize,
        winningTeamPrize: event.winningTeamPrize,
        runnerUpTeamPrize: event.runnerUpTeamPrize,
        runnerUpPrize: event.runnerUpPrize,
        minPlayers: event.minPlayers,
        maxPlayers: event.maxPlayers,
        pricePerPlayer: event.pricePerPlayer,
      },
    });
  }

  console.log("Sports events seeded successfully");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(async () => {
    await prisma.$disconnect();
  });
